version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0.1

workflows:
  verify:
    jobs:
      - orb-tools/lint:
          name: lint
      - orb-tools/pack:
          name: pack
          source-dir: src
      - orb-tools/publish:
          name: publish
          context: orb-publishing
          filters:
            branches:
              ignore: master
          checkout: false
          attach-workspace: true
          orb-ref: entur/helm@dev:$CIRCLE_BRANCH
          requires:
            - pack
      - orb-tools/increment:
          name: release
          context: orb-publishing
          filters:
            branches:
              only: master
          checkout: false
          attach-workspace: true
          orb-ref: entur/helm
          requires:
            - lint
            - pack
