description: |
  Demonstrate installing a helm chart with this orb.

usage:
  version: 2.1

orbs:
  helm: entur/helm@volatile # Use volatile if you always want the newest version.

jobs:
  deploy-application:
    docker:
      - image: entur/cci-toolbox:3.0 # This executor comes with a lof of pre-installed features; including gcloud.
        auth: # Add $DOCKERHUB_LOGIN and $DOCKERHUB_PASSWORD credentials in your context to log in to Docker hub
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - helm/install-helm-chart:
          chart: ./helm/$CIRCLE_PROJECT_REPONAME # file structure: helm/projectname/Chart.yaml
          namespace: $NAMESPACE # From Context
          release-name: $CIRCLE_PROJECT_REPONAME-my-release-$NAMESPACE # output: projectname-my-release-namespace
          wait: true # default true, this step is not needed

workflows:
  version: 2.1

  my-workflow:
    jobs:
      - deploy-application:
          name: deploy-to-kubernetes
          context: a-context-that-contain-namespace-env # This example uses the environment variable $NAMESPACE. It is not required otherwise.
